-- =====================================================================
-- Catálogo de etapas de selección — SIN datos sembrados (SGRH-61)
-- =====================================================================
-- Este archivo sembraba 20 etapas ("Recepción de CV", "Assessment Center",
-- "Prueba Psicométrica"…) tomadas de un embudo genérico de RRHH, no del
-- proceso real de la empresa.
--
-- El problema no era que sobraran: era que al ofrecerlas en el formulario
-- de avance, quien carga la postulación elige lo que más se le parece de
-- una lista ajena y el historial queda lleno de etapas que nunca pasaron.
-- Un historial inventado es peor que no tener historial, porque se lee como
-- dato bueno.
--
-- Desde SGRH-61 las etapas las crea cada empresa desde
-- Configuración → Etapas de selección, eligiendo a qué columna del tablero
-- pertenece cada una (postulados / en evaluación / decisión). La migración
-- 20260923000000 desactivó las que ya estaban sembradas.
--
-- El archivo se deja vacío a propósito y no se borra: así queda asentado
-- por qué no hay seed acá, y `sql_paths` sigue resolviendo sin cambios.
-- =====================================================================
